### ISSUE TITLE
Error after update to TYPO3 10: TypoScriptFrontendController must be constructed with a valid Site object or a resolved site in the current request as fallback. None given. 

### ISSUE THREAD

**Issue by klodeckl** [xperseguers/t3ext-ig_ldap_sso_auth#138]
After a TYPO3 Update 9 to 10 I get the following error when authenticating (backend and frontend):

Tue, 26 Apr 2022 10:27:56 +0200 [CRITICAL] request="4df08d59e391b" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1561583122: TypoScriptFrontendController must be constructed with a valid Site object or a resolved site in the current request as fallback. None given. | InvalidArgumentException thrown in file /var/www/typo3/typo3_src-10.4.27/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php in line 775. Requested URL: https://dev.oth-aw.de/typo3/?loginProvider=1433416747 - {"TYPO3_MODE":"BE","exception":"InvalidArgumentException: TypoScriptFrontendController must be constructed with a valid Site object or a resolved site in the current request as fallback. None given. in /var/www/typo3/typo3_src-10.4.27/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php:775\nStack trace:\n#0 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php(719): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->initializeSiteWithCompatibility(0, Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#1 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Utility/GeneralUtility.php(3480): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->__construct(Array, 0, '')\n#2 /var/cg/vhosts/dev/typo3conf/ext/ig_ldap_sso_auth/Classes/Library/Authentication.php(693): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::makeInstance('TYPO3\\\\CMS\\\\Front...', Array, 0, '')\n#3 /var/cg/vhosts/dev/typo3conf/ext/ig_ldap_sso_auth/Classes/Library/Authentication.php(244): Causal\\IgLdapSsoAuth\\Library\\Authentication::merge(Array, Array, Array)\n#4 /var/cg/vhosts/dev/typo3conf/ext/ig_ldap_sso_auth/Classes/Library/Authentication.php(123): Causal\\IgLdapSsoAuth\\Library\\Authentication::synchroniseUser('cn=ec,ou=Person...', 'ec')\n#5 /var/cg/vhosts/dev/typo3conf/ext/ig_ldap_sso_auth/Classes/Service/AuthenticationService.php(179): Causal\\IgLdapSsoAuth\\Library\\Authentication::ldapAuthenticate('ec', '34175867bEs')\n#6 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Authentication/AbstractUserAuthentication.php(645): Causal\\IgLdapSsoAuth\\Service\\AuthenticationService->getUser()\n#7 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Authentication/AbstractUserAuthentication.php(375): TYPO3\\CMS\\Core\\Authentication\\AbstractUserAuthentication->checkAuthentication()\n#8 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/backend/Classes/Middleware/BackendUserAuthenticator.php(70): TYPO3\\CMS\\Core\\Authentication\\AbstractUserAuthentication->start()\n#9 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#10 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#11 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#12 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(55): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#13 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#14 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php(75): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#15 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#16 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#17 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#18 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(78): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#19 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Http/AbstractApplication.php(85): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#20 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/backend/Classes/Http/Application.php(72): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#21 /var/www/typo3/typo3_src-10.4.27/typo3/sysext/core/Classes/Http/AbstractApplication.php(97): TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#22 /var/www/typo3/typo3_src-10.4.27/typo3/index.php(25): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#23 /var/www/typo3/typo3_src-10.4.27/typo3/index.php(26): {closure}()\n#24 {main}"}

**Comment by klodeckl** [comment]
I just tried the current master branch (3.7.0-dev): issue is gone.
